fix: jinja2.exceptions.TemplateNotFound blocked with multiprocessing
But I do not found the reason...

    Exception in thread Thread-3:
    Traceback (most recent call last):
      File "/path/to/python2.7/threading.py", line 810, in __bootstrap_inner
	self.run()
      File "/path/to/python2.7/threading.py", line 763, in run
	self.__target(*self.__args, **self.__kwargs)
      File "/path/to/python2.7/multiprocessing/pool.py", line 389, in _handle_results
	task = get()
    TypeError: ('__init__() takes at least 2 arguments (1 given)', <class 'jinja2.exceptions.TemplateNotFound'>, ())